const fr = {
  on: 'Allumée', off: 'Éteinte', unavailable: 'Indisponible', turnOn: 'Allumer', turnOff: 'Éteindre', brightness: 'Luminosité', details: 'Détails', error: 'Action impossible. Vérifiez la connexion et vos droits.',
  setup: 'Configuration MP Glass', intro: 'Configurez votre installation, puis créez votre dashboard.', name: 'Nom de la maison', scan: 'Analyser l’installation', save: 'Enregistrer', saved: 'Configuration enregistrée', review: 'À vérifier', devices: 'Équipements', auto: 'Classés automatiquement', noArea: 'Sans pièce', hidden: 'Masquer', preset: 'Apparence', generate: 'Créer le dashboard', generateHelp: 'Dans Tableaux de bord, ajoutez MP Glass Dashboard depuis les dashboards communautaires.', failed: 'Impossible de charger ou enregistrer. Vérifiez vos droits, la connexion et la version MP Glass.', why: 'Pourquoi cette carte ?', entity: 'Entité', reload: 'Recharger', unsupported: 'Non classé', export: 'Exporter le projet', area: 'Pièce', empty: 'Aucun équipement visible.', lights: 'Lumières', settings: 'Réglages', pending: 'En cours…', preview: 'Aperçu',
};
const en: Record<keyof typeof fr, string> = {
  on: 'On', off: 'Off', unavailable: 'Unavailable', turnOn: 'Turn on', turnOff: 'Turn off', brightness: 'Brightness', details: 'Details', error: 'Action failed. Check your connection and permissions.',
  setup: 'MP Glass Setup', intro: 'Configure your installation, then create your dashboard.', name: 'Home name', scan: 'Scan installation', save: 'Save', saved: 'Configuration saved', review: 'Needs review', devices: 'Devices', auto: 'Automatically classified', noArea: 'No room', hidden: 'Hide', preset: 'Appearance', generate: 'Create dashboard', generateHelp: 'In Dashboards, add MP Glass Dashboard from the community dashboards.', failed: 'Unable to load or save. Check permissions, connection and MP Glass version.', why: 'Why this card?', entity: 'Entity', reload: 'Reload', unsupported: 'Unclassified', export: 'Export project', area: 'Room', empty: 'No visible devices.', lights: 'Lights', settings: 'Settings', pending: 'Working…', preview: 'Preview',
};
export const t = (language: string | undefined, key: keyof typeof fr) => (language?.startsWith('fr') ? fr : en)[key];
