import './spatial/editor';
import { defaultSpatialPlan, type SpatialPlan } from '../shared/spatial';
import { LitElement, html, css, nothing, type TemplateResult } from 'lit';
import type { AppearanceConfig, MPHomeGraph, NavigationItem, Override, Preset } from '../shared/models';
import { MPDiscoveryEngine } from '../shared/discovery';
import { ensureDashboard, HARegistryReader, readProject, saveProject, type Hass, type ProjectResponse } from './ha/client';
import { glassStyles } from './styles';
import { t } from './i18n';
import { MP_GLASS_BACKGROUND } from './background';
import { mpIcon } from './icons';
import { defaultProject } from '../shared/project';

type StudioSection = 'spatial'|'identity'|'material'|'background'|'layout'|'content'|'navigation'|'devices';

export class MPGlassSettings extends LitElement {
  static styles = [glassStyles, css`
    :host{min-height:100%;display:block;background:radial-gradient(circle at 90% 0%,#263e60,transparent 48%),linear-gradient(145deg,#081321,#0a1a2a 55%,#07111d);padding:22px;box-sizing:border-box}main{max-width:1520px;margin:auto}.topbar{position:sticky;top:0;z-index:20;display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:18px;padding:14px 18px;border-radius:20px;background:rgba(6,20,35,.83);border:1px solid rgba(194,220,245,.18);box-shadow:0 16px 45px #0019;backdrop-filter:blur(22px)}.topbrand{display:flex;align-items:center;gap:13px}.logo{display:grid;place-items:center;width:44px;height:44px;border-radius:14px;background:linear-gradient(145deg,#56aaff33,#fff1);border:1px solid #9bd1ff55;color:#9ed2ff;font:30px Georgia,serif}.topbrand h1{font:27px/1 Georgia,serif;font-weight:400}.topbrand p{font-size:10px;letter-spacing:.18em;text-transform:uppercase;margin-top:5px}.top-actions{display:flex;gap:8px;align-items:center}.top-actions a,.top-actions button{min-height:44px;padding:0 14px;border-radius:13px;display:flex;align-items:center;gap:8px;text-decoration:none}.dashboard-link{color:#eaf6ff;border:1px solid #d9ecff2c;background:#fff1}.notice{margin:0 0 18px}
    .studio{display:grid;grid-template-columns:230px minmax(340px,.82fr) minmax(430px,1.18fr);gap:15px;align-items:start}.rail,.form-panel,.preview{border-radius:22px}.rail{position:sticky;top:92px;padding:12px;background:rgba(9,29,48,.7);border:1px solid rgba(211,231,250,.14);backdrop-filter:blur(20px)}.rail small{display:block;padding:8px 10px;color:#8fa8bd;letter-spacing:.18em;text-transform:uppercase;font-size:9px}.rail button{width:100%;min-height:47px!important;border:1px solid transparent!important;background:transparent!important;display:flex;align-items:center;gap:11px;text-align:left;padding:0 12px!important;border-radius:13px!important;color:#b9cad9!important}.rail button.active{color:white!important;background:linear-gradient(135deg,color-mix(in srgb,var(--mp-accent) 24%,transparent),rgba(255,255,255,.05))!important;border-color:color-mix(in srgb,var(--mp-accent) 42%,transparent)!important;box-shadow:inset 0 1px #fff1}.rail button.active svg{filter:drop-shadow(0 0 8px var(--mp-accent))}.rail .badge{margin-left:auto;min-width:24px;height:24px;border-radius:99px;display:grid;place-items:center;background:#fff1;font-size:10px}
    .studio.spatial{grid-template-columns:230px minmax(0,1fr)}.studio.spatial .preview{display:none}@media(max-width:760px){.studio.spatial{grid-template-columns:1fr}}
    .form-panel{min-height:600px;padding:24px}.panel-head{display:flex;align-items:flex-start;gap:13px;margin-bottom:20px}.panel-head .panel-icon{width:43px;height:43px;border-radius:14px;display:grid;place-items:center;background:color-mix(in srgb,var(--mp-accent) 15%,transparent);color:var(--mp-accent)}.panel-head h2{font:27px/1.1 Georgia,serif;font-weight:400}.panel-head p{font-size:12px;margin-top:6px}.preset-strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:4px 0 20px}.preset-choice{min-height:58px!important;padding:8px 10px!important;display:flex!important;align-items:center;gap:9px;text-align:left}.preset-choice.selected{border-color:var(--mp-accent)!important;background:color-mix(in srgb,var(--mp-accent) 18%,rgba(8,28,48,.4))!important;box-shadow:0 0 20px color-mix(in srgb,var(--mp-accent) 16%,transparent)}.preset-dot{width:23px;height:23px;flex:0 0 auto;border-radius:8px;border:1px solid #fff5;box-shadow:inset 0 1px #fff5}.preset-choice span:last-child{font-size:11px}.controls{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px 14px}.controls label{margin:0}.wide{grid-column:1/-1}.switch{display:flex!important;align-items:center;justify-content:space-between;min-height:52px;padding:0 13px;border:1px solid var(--mp-glass-border);border-radius:13px}.switch input{margin:0}.range-head{display:flex;justify-content:space-between;color:var(--mp-text-secondary);font-size:12px}.hint{padding:13px 14px;border-radius:13px;background:#6db8ff13;border:1px solid #76beff25;color:#b8cee1;font-size:12px;line-height:1.5}.nav-row{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid #dcecff16}.nav-row .handle{color:#8198ad}.mini-actions{display:flex;gap:5px}.mini-actions button{width:36px;min-height:36px!important;padding:0!important}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:18px}.stats div{padding:15px}.stats strong{font-size:27px}.device{padding:16px 0;border-bottom:1px solid var(--mp-glass-border)}.device label{min-width:170px}
    .preview{position:sticky;top:92px;min-height:620px;padding:18px;background-size:cover;background-position:center;color:white;overflow:hidden;border:1px solid #d7ebff3c;box-shadow:0 26px 65px #001b}.preview:before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(1,13,25,.72),rgba(2,17,30,.12)),rgba(2,12,23,var(--preview-dim,.44));pointer-events:none}.preview>*{position:relative}.preview-bar,.preview-card{background:rgb(from var(--preview-tint,#12344f) r g b / var(--preview-opacity,.62));border:1px solid color-mix(in srgb,var(--mp-accent) calc(var(--preview-border,.2)*100%),rgba(225,239,255,.35));box-shadow:0 16px 36px rgba(0,0,17,var(--preview-shadow,.35)),inset 0 1px #fff2;backdrop-filter:blur(var(--preview-blur,22px));border-radius:var(--preview-radius,22px)}.preview-bar{padding:12px 15px;display:flex;align-items:center;justify-content:space-between}.preview-brand{font:24px var(--preview-font,Georgia,serif)}.preview-nav{display:flex;gap:7px;font-size:11px}.preview-nav span{padding:8px 10px;border-radius:10px}.preview-nav .on{background:var(--mp-accent);color:white}.preview-hero{padding:clamp(44px,7vw,75px) 15px 38px;min-height:var(--preview-hero,300px)}.preview-hero small{letter-spacing:.22em;text-transform:uppercase}.preview-hero h2{font:42px/1 var(--preview-font,Georgia,serif);margin:13px 0}.preview-grid{display:grid;grid-template-columns:repeat(min(2,var(--preview-columns,2)),1fr);gap:var(--preview-gap,12px)}.preview-card{padding:17px;min-height:116px}.preview-card svg{color:#ffd969;filter:drop-shadow(0 0 10px #ffc83f)}.preview-card strong{display:block;margin-top:10px}.save-note{position:fixed;right:24px;bottom:24px;z-index:30;padding:13px 17px;border-radius:13px;background:#153f32;color:#bdf0cd;border:1px solid #67d99d55;box-shadow:0 14px 35px #0019}
    @media(max-width:1180px){.studio{grid-template-columns:200px 1fr}.preview{position:relative;top:0;grid-column:1/-1;min-height:520px}.rail{top:92px}}@media(max-width:760px){:host{padding:10px}.topbar{position:relative;display:block}.top-actions{margin-top:12px;flex-wrap:wrap}.studio{grid-template-columns:1fr}.rail{position:relative;top:0;display:flex;overflow:auto}.rail small{display:none}.rail button{min-width:max-content}.form-panel{padding:17px}.controls,.stats{grid-template-columns:1fr}.wide{grid-column:auto}.preview{grid-column:auto}.preset-strip{grid-template-columns:repeat(2,1fr)}}
  `];

  static properties = { hass:{attribute:false}, response:{state:true}, graph:{state:true}, busy:{state:true}, failure:{state:true}, saved:{state:true}, activeSection:{state:true}, inventoryOpen:{state:true}, inventoryPage:{state:true}, query:{state:true}, dashboard:{state:true} };
  hass?: Hass;
  private response?: ProjectResponse;
  private graph?: MPHomeGraph;
  private busy=false; private failure=false; private saved=false; private started=false;
  /** URL path of the MP Glass dashboard, "created" the first time the Studio adds it, "missing" when it could not. */
  private dashboard?:{urlPath:string;created:boolean}|'missing';
  private activeSection:StudioSection='identity';
  private inventoryOpen=false; private inventoryPage=0; private query='';
  private fallback?:{graph:MPHomeGraph;plan?:SpatialPlan};

  protected updated(){if(this.hass&&!this.started){this.started=true;const section=new URLSearchParams(location.search).get('section');if(section==='spatial')this.activeSection=section;void this.load();}}
  /** Schematic plan of the current HA areas, shown until a plan is saved. */
  private get defaultPlan(){if(!this.graph)return undefined;if(this.fallback?.graph!==this.graph)this.fallback={graph:this.graph,plan:defaultSpatialPlan(this.graph)};return this.fallback.plan;}
  private async load(){
    if(!this.hass||this.busy)return;this.busy=true;this.failure=false;
    try{const response=await readProject(this.hass);const defaults=defaultProject(response.project.project.name);this.response={...response,project:{...response.project,appearance:{...defaults.appearance,...response.project.appearance},navigation:response.project.navigation??defaults.navigation}};void this.linkDashboard();await this.scanInternal();}
    catch{this.failure=true;}finally{this.busy=false;}
  }
  /** Installing the integration only adds the Studio: the dashboard itself is added on its first opening. */
  private async linkDashboard(){
    if(!this.hass?.user?.is_admin||(this.dashboard&&this.dashboard!=='missing'))return;
    try{this.dashboard=await ensureDashboard(this.hass);}catch{this.dashboard='missing';}
  }
  private async scanInternal(){this.graph=MPDiscoveryEngine.discover(await HARegistryReader.read(this.hass!,true),this.response!.project);}
  private async scan(){if(!this.hass||!this.response||this.busy)return;this.busy=true;this.failure=false;try{await this.scanInternal();}catch{this.failure=true;}finally{this.busy=false;}}
  private override(key:string,patch:Override){if(!this.response)return;this.response={...this.response,project:{...this.response.project,overrides:{...this.response.project.overrides,[key]:{...this.response.project.overrides[key],...patch}}}};this.saved=false;}
  private appearance<K extends keyof AppearanceConfig>(key:K,value:AppearanceConfig[K]){if(!this.response)return;this.response={...this.response,project:{...this.response.project,appearance:{...this.response.project.appearance,[key]:value}}};this.setAttribute('preset',this.response.project.appearance.preset);this.saved=false;}
  private projectName(value:string){if(!this.response)return;this.response={...this.response,project:{...this.response.project,project:{...this.response.project.project,name:value}}};this.saved=false;}
  private navEnabled(item:NavigationItem,enabled:boolean){if(!this.response)return;const current=this.response.project.navigation.items;const items=enabled?[...current,item]:current.filter(value=>value!==item);if(!items.length)return;this.response={...this.response,project:{...this.response.project,navigation:{...this.response.project.navigation,items}}};this.saved=false;}
  private moveNav(item:NavigationItem,direction:-1|1){if(!this.response)return;const items=[...this.response.project.navigation.items];const from=items.indexOf(item),to=from+direction;if(from<0||to<0||to>=items.length)return;[items[from],items[to]]=[items[to]!,items[from]!];this.response={...this.response,project:{...this.response.project,navigation:{...this.response.project.navigation,items}}};this.saved=false;}
  private showNavLabels(value:boolean){if(!this.response)return;this.response={...this.response,project:{...this.response.project,navigation:{...this.response.project.navigation,showLabels:value}}};this.saved=false;}
  private async save(){if(!this.response||!this.hass||this.busy)return;this.busy=true;this.failure=false;this.saved=false;try{this.response=await saveProject(this.hass,this.response);this.saved=true;await this.scanInternal();}catch{this.failure=true;}finally{this.busy=false;}}
  private exportProject(){const url=URL.createObjectURL(new Blob([JSON.stringify(this.response?.project,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='mp-glass-project.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

  private head(icon:'palette'|'tune'|'home'|'rooms'|'bulb',title:string,description:string){return html`<div class="panel-head"><span class="panel-icon">${mpIcon(icon,22)}</span><div><h2>${title}</h2><p>${description}</p></div></div>`;}
  private renderIdentity(project:NonNullable<typeof this.response>['project']){const a=project.appearance;return html`${this.head('home','Identité','Le nom et la signature visuelle de cette installation')}<div class="controls"><label class="wide">Nom de la maison<input maxlength="100" .value=${project.project.name} @input=${(e:Event)=>this.projectName((e.target as HTMLInputElement).value)}></label><label class="wide">Accroche courte<input maxlength="100" .value=${a.eyebrow??''} @input=${(e:Event)=>this.appearance('eyebrow',(e.target as HTMLInputElement).value)}></label><p class="hint wide">Ces informations sont propres au chantier. Elles restent intactes lors d’une nouvelle détection des équipements.</p></div>`;}
  private renderMaterial(a:AppearanceConfig){return html`${this.head('palette','Style et matière','Presets, couleurs, verre et profondeur')}<div class="preset-strip">${([['glass-blue','Glass Blue','#68b8ff'],['glass-warm','Glass Warm','#eab98d'],['glass-dark','Glass Dark','#8da1b7'],['glass-light','Glass Light','#e8f0fa'],['glass-oled','Glass OLED','#07090d'],['glass-neutral','Glass Neutral','#80868e']] as [Preset,string,string][]).map(([value,label,color])=>html`<button class=${`preset-choice ${a.preset===value?'selected':''}`} @click=${()=>this.appearance('preset',value)}><span class="preset-dot" style=${`background:${color}`}></span><span>${label}</span></button>`)}</div><div class="controls"><label>Accent principal<input type="color" .value=${a.accent??'#69b7ff'} @input=${(e:Event)=>this.appearance('accent',(e.target as HTMLInputElement).value)}></label><label>Accent chaleureux<input type="color" .value=${a.secondaryAccent??'#efbd8b'} @input=${(e:Event)=>this.appearance('secondaryAccent',(e.target as HTMLInputElement).value)}></label><label>Teinte du verre<input type="color" .value=${a.glassTint??'#12344f'} @input=${(e:Event)=>this.appearance('glassTint',(e.target as HTMLInputElement).value)}></label><label>Typographie<select .value=${a.fontStyle??'elegant'} @change=${(e:Event)=>this.appearance('fontStyle',(e.target as HTMLSelectElement).value as AppearanceConfig['fontStyle'])}><option value="elegant">Élégante</option><option value="modern">Moderne</option><option value="soft">Douce</option></select></label>${this.range('Transparence du verre',25,90,Math.round((a.glassOpacity??.62)*100),'%',v=>this.appearance('glassOpacity',v/100),true)}${this.range('Flou du verre',0,40,a.glassBlur??22,'px',v=>this.appearance('glassBlur',v))}${this.range('Force des bordures',5,60,Math.round((a.borderStrength??.2)*100),'%',v=>this.appearance('borderStrength',v/100))}${this.range('Profondeur des ombres',0,80,Math.round((a.shadowStrength??.35)*100),'%',v=>this.appearance('shadowStrength',v/100))}${this.range('Arrondis',10,38,a.radius??22,'px',v=>this.appearance('radius',v))}</div>`;}
  private range(label:string,min:number,max:number,value:number,unit:string,onInput:(v:number)=>void,wide=false){return html`<label class=${wide?'wide':''}><span class="range-head"><span>${label}</span><strong>${value}${unit}</strong></span><input aria-label=${label} type="range" min=${min} max=${max} .value=${String(value)} @input=${(e:Event)=>onInput(Number((e.target as HTMLInputElement).value))}></label>`;}
  private renderBackground(a:AppearanceConfig){return html`${this.head('palette','Arrière-plan','Image, cadrage et traitement photographique')}<div class="controls"><label class="wide">Image Home Assistant<input placeholder="/local/mon-fond.webp" .value=${a.backgroundUrl??''} @input=${(e:Event)=>this.appearance('backgroundUrl',(e.target as HTMLInputElement).value||undefined)}></label><label>Position<select .value=${a.backgroundPosition??'right'} @change=${(e:Event)=>this.appearance('backgroundPosition',(e.target as HTMLSelectElement).value as AppearanceConfig['backgroundPosition'])}><option value="left">Gauche</option><option value="center">Centre</option><option value="right">Droite</option></select></label><span></span>${this.range('Assombrissement',0,80,Math.round((a.backgroundDim??.44)*100),'%',v=>this.appearance('backgroundDim',v/100),true)}${this.range('Flou photographique',0,20,a.backgroundBlur??0,'px',v=>this.appearance('backgroundBlur',v))}${this.range('Saturation',50,150,Math.round((a.backgroundSaturation??1)*100),'%',v=>this.appearance('backgroundSaturation',v/100))}<p class="hint wide">Utilisez un chemin local, par exemple /local/mp-glass/maison.webp. Les fichiers restent dans Home Assistant.</p></div>`;}
  private renderLayout(a:AppearanceConfig){return html`${this.head('tune','Disposition','Grille, densité, dimensions et contrôles')}<div class="controls"><label>Densité<select .value=${a.density??'comfortable'} @change=${(e:Event)=>this.appearance('density',(e.target as HTMLSelectElement).value as AppearanceConfig['density'])}><option value="comfortable">Confortable</option><option value="compact">Compacte</option></select></label><label>Style des cartes<select .value=${a.cardStyle??'standard'} @change=${(e:Event)=>this.appearance('cardStyle',(e.target as HTMLSelectElement).value as AppearanceConfig['cardStyle'])}><option value="compact">Compact</option><option value="standard">Standard</option><option value="spacious">Spacieux</option></select></label><label>Style des icônes<select .value=${a.iconStyle??'tile'} @change=${(e:Event)=>this.appearance('iconStyle',(e.target as HTMLSelectElement).value as AppearanceConfig['iconStyle'])}><option value="tile">Tuile</option><option value="orb">Cercle</option><option value="minimal">Minimal</option></select></label><span></span>${this.range('Colonnes sur grand écran',2,6,a.cardColumns??4,'',v=>this.appearance('cardColumns',v),true)}${this.range('Espacement',6,32,a.cardGap??12,'px',v=>this.appearance('cardGap',v))}${this.range('Largeur maximale',960,1920,a.maxWidth??1560,'px',v=>this.appearance('maxWidth',v))}${this.range('Hauteur du bandeau',220,620,a.heroHeight??455,'px',v=>this.appearance('heroHeight',v),true)}<label class="switch"><span>Détails des cartes</span><input type="checkbox" .checked=${a.showCardDetails!==false} @change=${(e:Event)=>this.appearance('showCardDetails',(e.target as HTMLInputElement).checked)}></label><label class="switch"><span>Curseurs de luminosité</span><input type="checkbox" .checked=${a.showBrightness!==false} @change=${(e:Event)=>this.appearance('showBrightness',(e.target as HTMLInputElement).checked)}></label></div>`;}
  private renderContent(a:AppearanceConfig){return html`${this.head('home','Contenu de l’accueil','Choisissez les textes et les sections visibles')}<div class="controls"><label class="wide">Sous-titre<input maxlength="160" .value=${a.subtitle??''} @input=${(e:Event)=>this.appearance('subtitle',(e.target as HTMLInputElement).value)}></label><label class="wide">Citation<input maxlength="180" .value=${a.quote??''} @input=${(e:Event)=>this.appearance('quote',(e.target as HTMLInputElement).value)}></label><label class="wide">Titre de la section<input maxlength="80" .value=${a.sectionTitle??''} @input=${(e:Event)=>this.appearance('sectionTitle',(e.target as HTMLInputElement).value)}></label><label class="wide">Description de la section<input maxlength="160" .value=${a.sectionSubtitle??''} @input=${(e:Event)=>this.appearance('sectionSubtitle',(e.target as HTMLInputElement).value)}></label>${([['showHero','Grand bandeau d’accueil'],['showOverview','Résumé de la maison'],['showClock','Horloge'],['showFooter','Signature en bas de page'],['showSettingsShortcut','Bouton Personnaliser'],['motion','Effets animés']] as [keyof AppearanceConfig,string][]).map(([key,label])=>html`<label class="switch"><span>${label}</span><input type="checkbox" .checked=${a[key]!==false} @change=${(e:Event)=>this.appearance(key,(e.target as HTMLInputElement).checked as never)}></label>`)}</div>`;}
  private renderNavigation(project:NonNullable<typeof this.response>['project']){const all:[NavigationItem,string][]=[['home','Accueil'],['lights','Lumières'],['rooms','Pièces']];const items=project.navigation.items;return html`${this.head('rooms','Navigation','Affichez et ordonnez les destinations principales')}<label class="switch"><span>Afficher les libellés</span><input type="checkbox" .checked=${project.navigation.showLabels} @change=${(e:Event)=>this.showNavLabels((e.target as HTMLInputElement).checked)}></label><div style="margin-top:18px">${all.map(([item,label])=>{const enabled=items.includes(item),index=items.indexOf(item);return html`<div class="nav-row"><span class="handle">${mpIcon(item==='home'?'home':item==='lights'?'bulb':'rooms',20)}</span><label class="switch" style="margin:0"><span>${label}</span><input aria-label=${label} type="checkbox" .checked=${enabled} ?disabled=${enabled&&items.length===1} @change=${(e:Event)=>this.navEnabled(item,(e.target as HTMLInputElement).checked)}></label><span class="mini-actions"><button aria-label=${`Monter ${label}`} ?disabled=${!enabled||index===0} @click=${()=>this.moveNav(item,-1)}>↑</button><button aria-label=${`Descendre ${label}`} ?disabled=${!enabled||index===items.length-1} @click=${()=>this.moveNav(item,1)}>↓</button></span></div>`;})}</div><p class="hint" style="margin-top:18px">Les pages Accueil, Lumières et Pièces sont générées automatiquement. Chaque pièce détectée dispose aussi de sa propre page.</p>`;}
  private renderDevices(project:NonNullable<typeof this.response>['project'],devices:NonNullable<MPHomeGraph['devices']>,review:NonNullable<MPHomeGraph['devices']>,lang:string|undefined){const inventory=devices.filter(d=>d.category==='generic'&&`${d.name} ${d.entityId}`.toLocaleLowerCase().includes(this.query.toLocaleLowerCase()));const page=Math.min(this.inventoryPage,Math.max(0,Math.ceil(inventory.length/25)-1));return html`${this.head('bulb','Équipements','Détection, associations et visibilité')}<div class="stats"><div class="surface"><strong>${devices.length}</strong><p>Entités</p></div><div class="surface"><strong>${devices.filter(d=>d.category==='light').length}</strong><p>Lumières</p></div><div class="surface"><strong>${review.length}</strong><p>À vérifier</p></div></div><button @click=${this.scan}>${mpIcon('scan',18)} ${t(lang,'scan')}</button>${review.map(d=>html`<div class="device"><strong>${d.name}</strong><p>${d.entityId}</p><div class="row"><label>Pièce<select aria-label="Pièce" .value=${project.overrides[d.entityKey]?.areaId??d.areaId??''} @change=${(e:Event)=>{const areaId=(e.target as HTMLSelectElement).value;if(areaId)this.override(d.entityKey,{areaId});}}><option value="">Aucune pièce</option>${this.graph?.areas.map(area=>html`<option value=${area.area_id}>${area.name}</option>`)}</select></label><label class="switch"><span>Masqué</span><input type="checkbox" .checked=${project.overrides[d.entityKey]?.hidden??d.hidden} @change=${(e:Event)=>this.override(d.entityKey,{hidden:(e.target as HTMLInputElement).checked})}></label></div><details><summary>Pourquoi cette carte ?</summary><pre>${JSON.stringify({evidence:d.evidence,capabilities:d.capabilities},null,2)}</pre></details></div>`)}${!review.length?html`<p class="hint" style="margin-top:18px">Aucune ambiguïté : les équipements reconnus sont prêts.</p>`:nothing}<details style="margin-top:20px" @toggle=${(e:Event)=>{this.inventoryOpen=(e.target as HTMLDetailsElement).open;}}><summary>Inventaire technique · ${inventory.length}</summary>${this.inventoryOpen?html`<label>Rechercher<input type="search" .value=${this.query} @input=${(e:Event)=>{this.query=(e.target as HTMLInputElement).value;this.inventoryPage=0;}}></label>${inventory.slice(page*25,page*25+25).map(d=>html`<div class="device"><strong>${d.name}</strong><p>${d.entityId}</p></div>`)}`:nothing}</details>`;}
  private renderSectionPanel(project:NonNullable<typeof this.response>['project'],devices:NonNullable<MPHomeGraph['devices']>,review:NonNullable<MPHomeGraph['devices']>,lang:string|undefined):TemplateResult{switch(this.activeSection){case'spatial':return html`<mp-spatial-editor .plan=${project.spatial} .fallback=${this.defaultPlan} .hass=${this.hass} .areas=${this.graph?.areas??[]} @spatial-change=${(e:CustomEvent<SpatialPlan>)=>{if(this.response){this.response={...this.response,project:{...this.response.project,spatial:e.detail}};this.saved=false;}}}></mp-spatial-editor>`;case'identity':return this.renderIdentity(project);case'material':return this.renderMaterial(project.appearance);case'background':return this.renderBackground(project.appearance);case'layout':return this.renderLayout(project.appearance);case'content':return this.renderContent(project.appearance);case'navigation':return this.renderNavigation(project);case'devices':return this.renderDevices(project,devices,review,lang);}}

  render(){
    const lang=this.hass?.locale?.language??this.hass?.language;const project=this.response?.project;const devices=this.graph?.devices.filter(d=>!d.disabled)??[];const review=devices.filter(d=>d.category!=='generic'&&!d.hidden&&(d.confidence<.9||!d.areaId||!this.graph?.areas.some(a=>a.area_id===d.areaId)));const a=project?.appearance;
    const font=a?.fontStyle==='modern'?'Inter,system-ui,sans-serif':a?.fontStyle==='soft'?'ui-rounded,system-ui,sans-serif':'Georgia,serif';
    const previewStyle=a?`--mp-accent:${a.accent??'#69b7ff'};--preview-tint:${a.glassTint??'#12344f'};--preview-opacity:${a.glassOpacity??.62};--preview-blur:${a.glassBlur??22}px;--preview-radius:${a.radius??22}px;--preview-dim:${a.backgroundDim??.44};--preview-border:${a.borderStrength??.2};--preview-shadow:${a.shadowStrength??.35};--preview-columns:${Math.min(2,a.cardColumns??4)};--preview-gap:${a.cardGap??12}px;--preview-hero:${Math.min(360,a.heroHeight??455)}px;--preview-font:${font};background-image:url(${a.backgroundUrl||MP_GLASS_BACKGROUND});background-position:${a.backgroundPosition??'right'} center;filter:saturate(${a.backgroundSaturation??1})`:'';
    const sections:[StudioSection,string,keyof typeof import('./icons')|string][]=[['spatial','Plan 3D','rooms'],['identity','Identité','home'],['material','Style & matière','palette'],['background','Arrière-plan','palette'],['layout','Disposition','tune'],['content','Contenu','home'],['navigation','Navigation','rooms'],['devices','Équipements','bulb']];
    return html`<main aria-busy=${this.busy}><div class="topbar"><div class="topbrand"><span class="logo">≋</span><div><h1>MP Glass Studio</h1><p>Personnalisation complète du dashboard</p></div></div>${project?html`<div class="top-actions">${this.dashboard==='missing'?html`<a class="dashboard-link" href="/config/lovelace/dashboards">${mpIcon('home',18)} Créer le dashboard</a>`:this.dashboard?html`<a class="dashboard-link" href=${`/${this.dashboard.urlPath}/home`}>${mpIcon('home',18)} Voir le dashboard</a>`:nothing}<button @click=${this.exportProject}>Exporter</button><button class="primary" ?disabled=${this.busy||!this.hass?.user?.is_admin} @click=${this.save}>${mpIcon('check',18)} Enregistrer</button></div>`:nothing}</div>${this.dashboard==='missing'?html`<p class="hint notice">Le dashboard n’a pas pu être ajouté automatiquement : Paramètres → Tableaux de bord → Ajouter un tableau de bord → MP Glass Dashboard.</p>`:this.dashboard?.created?html`<p class="hint notice">Dashboard « MP Glass » créé : il apparaît dans la barre latérale de Home Assistant.</p>`:nothing}${this.failure?html`<p role="alert" class="error">Impossible de charger ou sauvegarder la configuration.</p><button @click=${this.load}>Recharger</button>`:nothing}${project&&a?html`<div class=${this.activeSection==='spatial'?'studio spatial':'studio'}><aside class="rail"><small>Personnaliser</small>${sections.map(([id,label,icon])=>html`<button class=${this.activeSection===id?'active':''} @click=${()=>{this.activeSection=id;}}>${mpIcon(icon as 'home',19)}<span>${label}</span>${id==='devices'&&review.length?html`<span class="badge">${review.length}</span>`:nothing}</button>`)}</aside><section class="form-panel surface">${this.renderSectionPanel(project,devices,review,lang)}</section><section class="preview" style=${previewStyle} aria-label="Aperçu en direct"><div class="preview-bar"><span class="preview-brand">≋ ${project.project.name}</span><span class="preview-nav">${project.navigation.items.map((item,index)=>html`<span class=${index===0?'on':''}>${project.navigation.showLabels?({home:'Accueil',lights:'Lumières',rooms:'Pièces'}[item]):mpIcon(item==='home'?'home':item==='lights'?'bulb':'rooms',15)}</span>`)}</span></div>${a.showHero===false?nothing:html`<div class="preview-hero"><small>${a.eyebrow}</small><h2>Bonsoir,<br>la maison est avec vous.</h2><span>${a.subtitle}</span></div>`}<div class="preview-grid"><div class="preview-card">${mpIcon('bulb',26)}<strong>${a.sectionTitle||'Lumières'}</strong><small>Prêtes à contrôler</small></div><div class="preview-card">${mpIcon('rooms',26)}<strong>Pièces</strong><small>Organisation automatique</small></div></div></section></div>`:this.busy?html`<p role="status">Chargement du Studio…</p>`:nothing}${this.saved?html`<p role="status" class="save-note">Configuration enregistrée · le dashboard est à jour</p>`:nothing}</main>`;
  }
}
